name: Coverage
on:
  push:
    paths:
      - 'src/**/*.ts'
      - '__tests__/**/*.ts'
      - 'package.json'
      - '.github/workflows/coverage.yml'
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Free Pascal
        run: sudo apt-get install --no-install-recommends -y fpc
      - run: npm ci
      - run: npm run build --if-present
      - name: Run tests
        run: npm run coverage
      - name: Send coverage info to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/cobertura-coverage.xml
