name: Unit Tests

on:
  push:
    paths:
      - 'src/**/*.js'
      - '__tests__/**/*.js'
      - 'package.json'
      - '.github/workflows/test.yml'
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [v16.x, v18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: mskelton/setup-yarn@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Free Pascal
        run: sudo apt-get install --no-install-recommends -y fpc
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run tests
        run: yarn test
